depthimage_to_laserscan:
  ros__parameters:
    scan_height: 5 # (int, default: 1 pixel)
    scan_time: 0.033 # (double, default: 1/30.0Hz (0.033s))
    range_min: 0.45 # (double, default: 0.45m)
    range_max: 10.0 # (double, default: 10.0m)
    output_frame: "camera_depth_frame" # (str, default: camera_depth_frame)

